/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Laporan;
import java.awt.BorderLayout;
import javax.swing.JPanel;

public class MenuLaporan extends javax.swing.JPanel {

    /**
     * Creates new form MenuLaporan
     */
    public MenuLaporan() {
        initComponents();
    switchPanel(new Laporan.LaporanPelanggan1());
    
    revalidate();
    repaint();
    }
   private void switchPanel(JPanel panel) {
    PanelUtama.removeAll();
    PanelUtama.setLayout(new BorderLayout());
    PanelUtama.add(panel, BorderLayout.CENTER);
    PanelUtama.revalidate();
    PanelUtama.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lppelanggan = new javax.swing.JButton();
        Lppaket = new javax.swing.JButton();
        Lpteknisi = new javax.swing.JButton();
        Lppendapatan = new javax.swing.JButton();
        PanelUtama = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        Lppelanggan.setText("Laporan Pelanggan");
        Lppelanggan.addActionListener(this::LppelangganActionPerformed);

        Lppaket.setText("Laporan Paket");
        Lppaket.addActionListener(this::LppaketActionPerformed);

        Lpteknisi.setText("Laporan Teknisi");
        Lpteknisi.addActionListener(this::LpteknisiActionPerformed);

        Lppendapatan.setText("Laporan Pendapatan");
        Lppendapatan.addActionListener(this::LppendapatanActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Lppelanggan)
                .addGap(48, 48, 48)
                .addComponent(Lppaket)
                .addGap(37, 37, 37)
                .addComponent(Lpteknisi)
                .addGap(30, 30, 30)
                .addComponent(Lppendapatan)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lppelanggan)
                    .addComponent(Lppaket)
                    .addComponent(Lpteknisi)
                    .addComponent(Lppendapatan))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        PanelUtama.setLayout(new java.awt.CardLayout());
        add(PanelUtama, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void LppaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LppaketActionPerformed
        switchPanel(new Laporan.LaporanPaket1());
    }//GEN-LAST:event_LppaketActionPerformed

    private void LppelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LppelangganActionPerformed
         PanelUtama.removeAll();
    PanelUtama.setLayout(new BorderLayout());
    PanelUtama.add(new Laporan.LaporanPelanggan1(), BorderLayout.CENTER);
    PanelUtama.revalidate();
    PanelUtama.repaint();
    }//GEN-LAST:event_LppelangganActionPerformed

    private void LpteknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpteknisiActionPerformed
          switchPanel(new Laporan.LaporanTeknisi1());
    }//GEN-LAST:event_LpteknisiActionPerformed

    private void LppendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LppendapatanActionPerformed
          switchPanel(new Laporan.LaporanPendapatan1());
    }//GEN-LAST:event_LppendapatanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lppaket;
    private javax.swing.JButton Lppelanggan;
    private javax.swing.JButton Lppendapatan;
    private javax.swing.JButton Lpteknisi;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
