/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formform;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.BorderLayout;

/**
 *
 * @author Admin
 */
public class Dashboard1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard1.class.getName());

    /**
     * Creates new form Dashboard1
     */
    public Dashboard1() {
        initComponents();
        this.setLocationRelativeTo(null);
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
private void switchPanel(JPanel panel) {
    jMainPanel.removeAll();
    jMainPanel.setLayout(new BorderLayout());
    jMainPanel.add(panel, BorderLayout.CENTER);
    jMainPanel.revalidate();
    jMainPanel.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameKiri = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        txtPelanggan = new javax.swing.JLabel();
        txtPaketInet = new javax.swing.JLabel();
        txtTeknisi = new javax.swing.JLabel();
        txtRouter = new javax.swing.JLabel();
        txtLangganan = new javax.swing.JLabel();
        txtTransaksi = new javax.swing.JLabel();
        txtLaporan = new javax.swing.JLabel();
        jLabelLaporan = new javax.swing.JLabel();
        jLabelTransaksi = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jLabelRouter = new javax.swing.JLabel();
        jLabelPKT = new javax.swing.JLabel();
        jLabelPelanggan = new javax.swing.JLabel();
        jLabelLangganan = new javax.swing.JLabel();
        jLabelTeknisi = new javax.swing.JLabel();
        jLabelLogoHeader = new javax.swing.JLabel();
        FrameAtas = new javax.swing.JPanel();
        jDashboard1 = new javax.swing.JLabel();
        jMainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrameKiri.setBackground(new java.awt.Color(255, 255, 255));
        FrameKiri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        FrameKiri.setForeground(new java.awt.Color(204, 204, 204));

        txtDashboard.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(153, 153, 153));
        txtDashboard.setText("Dashboard");
        txtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDashboardMouseClicked(evt);
            }
        });

        txtPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPelanggan.setForeground(new java.awt.Color(153, 153, 153));
        txtPelanggan.setText("Pelanggan");
        txtPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPelangganMouseClicked(evt);
            }
        });

        txtPaketInet.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPaketInet.setForeground(new java.awt.Color(153, 153, 153));
        txtPaketInet.setText("Paket Internet");
        txtPaketInet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPaketInetMouseClicked(evt);
            }
        });

        txtTeknisi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTeknisi.setForeground(new java.awt.Color(153, 153, 153));
        txtTeknisi.setText("Teknisi");
        txtTeknisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTeknisiMouseClicked(evt);
            }
        });

        txtRouter.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtRouter.setForeground(new java.awt.Color(153, 153, 153));
        txtRouter.setText("Router");
        txtRouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRouterMouseClicked(evt);
            }
        });

        txtLangganan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtLangganan.setForeground(new java.awt.Color(153, 153, 153));
        txtLangganan.setText("Langganan");
        txtLangganan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLanggananMouseClicked(evt);
            }
        });

        txtTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTransaksi.setForeground(new java.awt.Color(153, 153, 153));
        txtTransaksi.setText("Transaksi");
        txtTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTransaksiMouseClicked(evt);
            }
        });

        txtLaporan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtLaporan.setForeground(new java.awt.Color(153, 153, 153));
        txtLaporan.setText("Laporan");

        jLabelLaporan.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelLaporan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\bookmark1.png")); // NOI18N
        jLabelLaporan.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelLaporan.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabelTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelTransaksi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\newspaper1.png")); // NOI18N
        jLabelTransaksi.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelTransaksi.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabelHome.setBackground(new java.awt.Color(153, 153, 153));
        jLabelHome.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(204, 204, 204));
        jLabelHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\home1.png")); // NOI18N
        jLabelHome.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelHome.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabelRouter.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelRouter.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\router1.png")); // NOI18N
        jLabelRouter.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelRouter.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabelPKT.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelPKT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\internet-speed-wifi1.png")); // NOI18N
        jLabelPKT.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelPKT.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabelPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelPelanggan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\users-alt1.png")); // NOI18N
        jLabelPelanggan.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelPelanggan.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabelLangganan.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelLangganan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\list-check1.png")); // NOI18N
        jLabelLangganan.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelLangganan.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabelTeknisi.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelTeknisi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\user-plumber1.png")); // NOI18N
        jLabelTeknisi.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelTeknisi.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabelLogoHeader.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabelLogoHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogoHeader.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\Icon\\Putra.Net.png")); // NOI18N
        jLabelLogoHeader.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelLogoHeader.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout FrameKiriLayout = new javax.swing.GroupLayout(FrameKiri);
        FrameKiri.setLayout(FrameKiriLayout);
        FrameKiriLayout.setHorizontalGroup(
            FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameKiriLayout.createSequentialGroup()
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FrameKiriLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelRouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameKiriLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelLangganan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTeknisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelPKT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameKiriLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPaketInet)
                            .addComponent(txtPelanggan)
                            .addComponent(txtTeknisi)
                            .addComponent(txtRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLangganan)
                            .addComponent(txtTransaksi)
                            .addComponent(txtLaporan))))
                .addGap(66, 66, 66))
            .addGroup(FrameKiriLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelLogoHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrameKiriLayout.setVerticalGroup(
            FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameKiriLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelLogoHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDashboard)
                    .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPelanggan)
                    .addComponent(jLabelPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPaketInet)
                    .addComponent(jLabelPKT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTeknisi)
                    .addComponent(jLabelTeknisi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(FrameKiriLayout.createSequentialGroup()
                        .addComponent(txtRouter)
                        .addGap(33, 33, 33)
                        .addComponent(txtLangganan))
                    .addGroup(FrameKiriLayout.createSequentialGroup()
                        .addComponent(jLabelRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLangganan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTransaksi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(FrameKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLaporan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(328, Short.MAX_VALUE))
        );

        getContentPane().add(FrameKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 882));

        FrameAtas.setBackground(new java.awt.Color(255, 255, 255));
        FrameAtas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jDashboard1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDashboard1.setForeground(new java.awt.Color(153, 153, 153));
        jDashboard1.setText("SELAMAT DATANG BOS QUUU!");

        javax.swing.GroupLayout FrameAtasLayout = new javax.swing.GroupLayout(FrameAtas);
        FrameAtas.setLayout(FrameAtasLayout);
        FrameAtasLayout.setHorizontalGroup(
            FrameAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameAtasLayout.createSequentialGroup()
                .addContainerGap(953, Short.MAX_VALUE)
                .addComponent(jDashboard1)
                .addGap(25, 25, 25))
        );
        FrameAtasLayout.setVerticalGroup(
            FrameAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAtasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jDashboard1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(FrameAtas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1250, 70));

        jMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jMainPanel.setForeground(new java.awt.Color(255, 255, 255));
        jMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 1240, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseClicked
        // TODO add your handling code here:
         switchPanel(new mendash());                              
    }//GEN-LAST:event_txtDashboardMouseClicked

    private void txtPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPelangganMouseClicked
        // TODO add your handling code here:
        switchPanel(new Pelanggan1());                              
    }//GEN-LAST:event_txtPelangganMouseClicked

    private void txtPaketInetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPaketInetMouseClicked
        // TODO add your handling code here:
        switchPanel(new DaftarPaket());
    }//GEN-LAST:event_txtPaketInetMouseClicked

    private void txtTeknisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTeknisiMouseClicked
        // TODO add your handling code here:
        switchPanel(new Teknisi1());                              
    }//GEN-LAST:event_txtTeknisiMouseClicked

    private void txtRouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRouterMouseClicked
        // TODO add your handling code here:
        switchPanel(new Router1());                              
    }//GEN-LAST:event_txtRouterMouseClicked

    private void txtLanggananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLanggananMouseClicked
        // TODO add your handling code here:
        switchPanel(new Langganan1());                              
    }//GEN-LAST:event_txtLanggananMouseClicked

    private void txtTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTransaksiMouseClicked
        // TODO add your handling code here:
        switchPanel(new Transaksi1());                             
    }//GEN-LAST:event_txtTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FrameAtas;
    private javax.swing.JPanel FrameKiri;
    private javax.swing.JLabel jDashboard1;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelLangganan;
    private javax.swing.JLabel jLabelLaporan;
    private javax.swing.JLabel jLabelLogoHeader;
    private javax.swing.JLabel jLabelPKT;
    private javax.swing.JLabel jLabelPelanggan;
    private javax.swing.JLabel jLabelRouter;
    private javax.swing.JLabel jLabelTeknisi;
    private javax.swing.JLabel jLabelTransaksi;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtLangganan;
    private javax.swing.JLabel txtLaporan;
    private javax.swing.JLabel txtPaketInet;
    private javax.swing.JLabel txtPelanggan;
    private javax.swing.JLabel txtRouter;
    private javax.swing.JLabel txtTeknisi;
    private javax.swing.JLabel txtTransaksi;
    // End of variables declaration//GEN-END:variables
}
