/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formform;

/**
 *
 * @author User
 */
public class mendash extends javax.swing.JPanel {

    /**
     * Creates new form mendash
     */
    public mendash() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmendash = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbpen = new javax.swing.JLabel();
        lbtpen = new javax.swing.JLabel();
        lbval1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbpel = new javax.swing.JLabel();
        lbtot = new javax.swing.JLabel();
        lbval3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbtrans = new javax.swing.JLabel();
        lbttr = new javax.swing.JLabel();
        lbval5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbtek = new javax.swing.JLabel();
        lbttek = new javax.swing.JLabel();
        lbval7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jmendash.setBackground(new java.awt.Color(255, 255, 255));
        jmendash.setPreferredSize(new java.awt.Dimension(1130, 790));
        jmendash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(228, 139));

        lbpen.setBackground(new java.awt.Color(255, 255, 255));
        lbpen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbpen.setForeground(new java.awt.Color(51, 51, 51));
        lbpen.setText("Pendapatan");

        lbtpen.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbtpen.setForeground(new java.awt.Color(51, 51, 51));
        lbtpen.setText("Rp 5,4 jt");

        lbval1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbval1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/People.png"))); // NOI18N
        lbval1.setText("100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbtpen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbval1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtpen)
                    .addComponent(lbval1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jmendash.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 20, 241, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbpel.setBackground(new java.awt.Color(153, 153, 153));
        lbpel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbpel.setForeground(new java.awt.Color(51, 51, 51));
        lbpel.setText("Pelanggan");

        lbtot.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbtot.setForeground(new java.awt.Color(51, 51, 51));
        lbtot.setText("100");

        lbval3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbval3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/People.png"))); // NOI18N
        lbval3.setText("100");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbpel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbtot, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbval3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbpel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtot)
                    .addComponent(lbval3))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jmendash.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 140));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(228, 139));

        lbtrans.setBackground(new java.awt.Color(255, 255, 255));
        lbtrans.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbtrans.setForeground(new java.awt.Color(51, 51, 51));
        lbtrans.setText("Transaksi");

        lbttr.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbttr.setForeground(new java.awt.Color(51, 51, 51));
        lbttr.setText("100");

        lbval5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbval5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/People.png"))); // NOI18N
        lbval5.setText("100");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtrans, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbttr, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbval5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbtrans)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbttr))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbval5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmendash.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(228, 139));

        lbtek.setBackground(new java.awt.Color(255, 255, 255));
        lbtek.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbtek.setForeground(new java.awt.Color(51, 51, 51));
        lbtek.setText("Teknisi Aktif");

        lbttek.setBackground(new java.awt.Color(204, 204, 204));
        lbttek.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbttek.setForeground(new java.awt.Color(51, 51, 51));
        lbttek.setText("100");

        lbval7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbval7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/People.png"))); // NOI18N
        lbval7.setText("100");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtek, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbttek, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbval7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbtek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbttek))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbval7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmendash.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Riwayat Transaksi");
        jmendash.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, 244, -1));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Pelanggan", "Paket", "Total ", "Tanggal"
            }
        ));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jmendash.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 272, 1026, 280));

        add(jmendash, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jmendash;
    private javax.swing.JLabel lbpel;
    private javax.swing.JLabel lbpen;
    private javax.swing.JLabel lbtek;
    private javax.swing.JLabel lbtot;
    private javax.swing.JLabel lbtpen;
    private javax.swing.JLabel lbtrans;
    private javax.swing.JLabel lbttek;
    private javax.swing.JLabel lbttr;
    private javax.swing.JLabel lbval1;
    private javax.swing.JLabel lbval3;
    private javax.swing.JLabel lbval5;
    private javax.swing.JLabel lbval7;
    // End of variables declaration//GEN-END:variables
}
