/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormLogin;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import session.UserID;

/**
 *
 * @author User
 */
public class form_login1 extends javax.swing.JFrame{
private Connection conn = new koneksi().connect();
char defaultEcho;
    /**
     * Creates new form form_login
     */
    public form_login1() {
        initComponents();
    defaultEcho = jpw.getEchoChar();
        
          this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelKiri = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLogin = new javax.swing.JLabel();
        jUsername = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        jPassword = new javax.swing.JLabel();
        jpw = new javax.swing.JPasswordField();
        blog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelKiri.setBackground(new java.awt.Color(15, 23, 42));
        jPanelKiri.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelKiriAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanelKiri.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLogin.setBackground(new java.awt.Color(255, 255, 255));
        jLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLogin.setForeground(new java.awt.Color(79, 70, 229));
        jLogin.setText("Login Page");
        jPanel1.add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1235, 93, -1, -1));

        jUsername.setBackground(new java.awt.Color(0, 102, 255));
        jUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jUsername.setForeground(new java.awt.Color(51, 51, 51));
        jUsername.setText("Username");
        jPanel1.add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 204, -1, -1));

        txtnm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnm.setForeground(new java.awt.Color(204, 204, 204));
        txtnm.setText("Type your username");
        txtnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnmFocusLost(evt);
            }
        });
        txtnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmActionPerformed(evt);
            }
        });
        txtnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnmKeyPressed(evt);
            }
        });
        jPanel1.add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 236, 283, 40));

        jPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(51, 51, 51));
        jPassword.setText("Password");
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 294, -1, -1));

        jpw.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jpw.setForeground(new java.awt.Color(204, 204, 204));
        jpw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpwFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpwFocusLost(evt);
            }
        });
        jpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwActionPerformed(evt);
            }
        });
        jpw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpwKeyPressed(evt);
            }
        });
        jPanel1.add(jpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 326, 283, 40));

        blog.setBackground(new java.awt.Color(79, 70, 229));
        blog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blog.setForeground(new java.awt.Color(255, 255, 255));
        blog.setText("Masuk");
        blog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogActionPerformed(evt);
            }
        });
        jPanel1.add(blog, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 394, 236, 41));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Putra.Net3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 84, 285, 114));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -908;
        gridBagConstraints.ipady = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(140, 263, 126, 267);
        jPanelKiri.add(jPanel1, gridBagConstraints);

        getContentPane().add(jPanelKiri, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(948, 848));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelKiriAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelKiriAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelKiriAncestorAdded

    private void blogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM admin WHERE admin=? AND password=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtnm.getText());
            pst.setString(2, jpw.getText());

            ResultSet hasil = pst.executeQuery();
            if (hasil.next()) {
                UserID.setUserLogin(hasil.getString("admin"));
                JOptionPane.showMessageDialog(this, "Login berhasil");
                this.setVisible(false);
                new Dashboard.Dashboard1().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Username dan password salah");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Login gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_blogActionPerformed

    private void jpwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            blog.doClick();
        }
    }//GEN-LAST:event_jpwKeyPressed

    private void jpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwActionPerformed

    private void jpwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpwFocusLost
        if (jpw.getText().equals("")) {
            jpw.setText("Masukkan Password");
            jpw.setEchoChar((char)0);
        }
    }//GEN-LAST:event_jpwFocusLost

    private void jpwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpwFocusGained
        if (String.valueOf(jpw.getPassword()).equals("Masukkan Password")) {
            jpw.setText("");
        }
    }//GEN-LAST:event_jpwFocusGained

    private void txtnmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnmKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jpw.requestFocus();
        }
    }//GEN-LAST:event_txtnmKeyPressed

    private void txtnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmActionPerformed

    private void txtnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnmFocusLost
        if (txtnm.getText().equals("")) {
            txtnm.setText("Type your username");
        }
    }//GEN-LAST:event_txtnmFocusLost

    private void txtnmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnmFocusGained
        if (String.valueOf(txtnm.getText()).equals("Type your username")) {
            txtnm.setText("");
        }
    }//GEN-LAST:event_txtnmFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
                new form_login1().setVisible(true);               
            }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelKiri;
    private javax.swing.JLabel jPassword;
    private javax.swing.JLabel jUsername;
    private javax.swing.JPasswordField jpw;
    private javax.swing.JTextField txtnm;
    // End of variables declaration//GEN-END:variables
}


