/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormLogin;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.koneksi;


/**
 *
 * @author User
 */
public class form_login1 extends javax.swing.JFrame{
private Connection conn = new koneksi().connect();
char defaultEcho;
    /**
     * Creates new form form_login
     */
    public form_login1() {
        initComponents();
    defaultEcho = jpw.getEchoChar();
        hide.setVisible(false);
          this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelKiri = new javax.swing.JPanel();
        jPassword = new javax.swing.JLabel();
        jLogin = new javax.swing.JLabel();
        blog = new javax.swing.JButton();
        txtnm = new javax.swing.JTextField();
        hide = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jpw = new javax.swing.JPasswordField();
        jUsername = new javax.swing.JLabel();
        jPanelKanan = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelKiri.setBackground(new java.awt.Color(15, 23, 42));
        jPanelKiri.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelKiriAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.setText("Password");

        jLogin.setBackground(new java.awt.Color(255, 255, 255));
        jLogin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLogin.setText("LOGIN");

        blog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        blog.setText("Login");
        blog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogActionPerformed(evt);
            }
        });

        txtnm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnm.setForeground(new java.awt.Color(204, 204, 204));
        txtnm.setText("Type your username");
        txtnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnmFocusLost(evt);
            }
        });
        txtnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmActionPerformed(evt);
            }
        });
        txtnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnmKeyPressed(evt);
            }
        });

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Blind.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Eye.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });

        jpw.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jpw.setForeground(new java.awt.Color(204, 204, 204));
        jpw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpwFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpwFocusLost(evt);
            }
        });
        jpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwActionPerformed(evt);
            }
        });
        jpw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpwKeyPressed(evt);
            }
        });

        jUsername.setBackground(new java.awt.Color(0, 0, 0));
        jUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jUsername.setForeground(new java.awt.Color(255, 255, 255));
        jUsername.setText("Username");

        jPanelKanan.setBackground(new java.awt.Color(255, 255, 255));
        jPanelKanan.setLayout(new java.awt.BorderLayout());

        jLogo.setBackground(new java.awt.Color(102, 204, 255));
        jPanelKanan.add(jLogo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelKiriLayout = new javax.swing.GroupLayout(jPanelKiri);
        jPanelKiri.setLayout(jPanelKiriLayout);
        jPanelKiriLayout.setHorizontalGroup(
            jPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKiriLayout.createSequentialGroup()
                .addGroup(jPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKiriLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelKiriLayout.createSequentialGroup()
                                .addComponent(jpw, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(jPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hide)
                                    .addComponent(show)))
                            .addComponent(jUsername)
                            .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPassword)))
                    .addGroup(jPanelKiriLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLogin))
                    .addGroup(jPanelKiriLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(blog, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addComponent(jPanelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE))
        );
        jPanelKiriLayout.setVerticalGroup(
            jPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelKiriLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLogin)
                .addGap(25, 25, 25)
                .addComponent(jUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelKiriLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hide)
                            .addComponent(show))))
                .addGap(18, 18, 18)
                .addComponent(blog)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelKiri, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1615, 944));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelKiriAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelKiriAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelKiriAncestorAdded

    private void jpwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            blog.doClick();
        }
    }//GEN-LAST:event_jpwKeyPressed

    private void jpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwActionPerformed

    private void jpwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpwFocusLost
        if (jpw.getText().equals("")) {
            jpw.setText("Masukkan Password");
            jpw.setEchoChar((char)0);
        }
    }//GEN-LAST:event_jpwFocusLost

    private void jpwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpwFocusGained
        if (String.valueOf(jpw.getPassword()).equals("Masukkan Password")) {
            jpw.setText("");
        }
    }//GEN-LAST:event_jpwFocusGained

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        show.setVisible(false);
        hide.setVisible(true);
        jpw.setEchoChar((char)0);
    }//GEN-LAST:event_showMouseClicked

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        show.setVisible(true);
        hide.setVisible(false);
        jpw.setEchoChar(defaultEcho);
    }//GEN-LAST:event_hideMouseClicked

    private void txtnmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnmKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jpw.requestFocus();
        }
    }//GEN-LAST:event_txtnmKeyPressed

    private void txtnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmActionPerformed

    private void txtnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnmFocusLost
        if (txtnm.getText().equals("")) {
            txtnm.setText("Type your username");
        }
    }//GEN-LAST:event_txtnmFocusLost

    private void txtnmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnmFocusGained
        if (String.valueOf(txtnm.getText()).equals("Type your username")) {
            txtnm.setText("");
        }
    }//GEN-LAST:event_txtnmFocusGained

    private void blogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM admin WHERE admin=? AND password=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtnm.getText());
            pst.setString(2, jpw.getText());

            ResultSet hasil = pst.executeQuery();
            if (hasil.next()) {

                JOptionPane.showMessageDialog(this, "Login berhasil");
                this.setVisible(false);
                new Dashboard.Dashboard1().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Username dan password salah");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Login gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_blogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
                new form_login1().setVisible(true);               
            }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blog;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLogin;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanelKanan;
    private javax.swing.JPanel jPanelKiri;
    private javax.swing.JLabel jPassword;
    private javax.swing.JLabel jUsername;
    private javax.swing.JPasswordField jpw;
    private javax.swing.JLabel show;
    private javax.swing.JTextField txtnm;
    // End of variables declaration//GEN-END:variables
}


